// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqzbwkrqwysvfawkmhzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxemJ3a3Jxd3lzdmZhd2ttaHpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNjI5MTMsImV4cCI6MjA3MjczODkxM30.KD-9agVLyAEQX4pGged3EwxvO2gW_D8-0bjJ0IKZYOU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});